<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '1'))?>"><div class="item item-1"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '2'))?>"><div class="item item-2"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '3'))?>"><div class="item item-3"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '4'))?>"><div class="item item-4"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '5'))?>"><div class="item item-5"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '6'))?>"><div class="item item-6"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '7'))?>"><div class="item item-7"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '8'))?>"><div class="item item-8"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '9'))?>"><div class="item item-9"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '10'))?>"><div class="item item-10"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '11'))?>"><div class="item item-11"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '12'))?>"><div class="item item-12"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '13'))?>"><div class="item item-13"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '14'))?>"><div class="item item-14"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '15'))?>"><div class="item item-15"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '16'))?>"><div class="item item-16"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '17'))?>"><div class="item item-17"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '18'))?>"><div class="item item-18"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '19'))?>"><div class="item item-19"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '20'))?>"><div class="item item-20"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '21'))?>"><div class="item item-21"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '22'))?>"><div class="item item-22"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '23'))?>"><div class="item item-23"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '24'))?>"><div class="item item-24"></div></a>
<a href="<?php echo Yii::app()->createUrl('Item/DisplayItem', array('bookid' => '25'))?>"><div class="item item-25"></div></a>